oc20_elem_refs:
- 0.0
- -0.16141512
- 0.03262098
- -0.04787699
- -0.06299825
- -0.14979306
- -0.11657468
- -0.10862579
- -0.10298174
- -0.03420248
- 0.02673997
- -0.03729558
- 0.00515243
- -0.07535697
- -0.13663351
- -0.12922852
- -0.11796547
- -0.07802946
- -0.00672682
- -0.04089589
- -0.00024177
- -1.74545186
- -1.54220241
- -1.0934019
- -1.16168372
- -1.23073475
- -0.78852824
- -0.71851599
- -0.52465053
- -0.02692092
- -0.00317922
- -0.06266862
- -0.10835274
- -0.12394474
- -0.11351727
- -0.07455817
- -0.00258354
- -0.04111325
- -0.02090265
- -1.89306078
- -1.30591887
- -0.63320009
- -0.26230344
- -0.2633669
- -0.5160055
- -0.95950798
- -1.45589361
- -0.0429969
- -0.00026949
- -0.05925609
- -0.09734631
- -0.12406852
- -0.11427538
- -0.07021442
- 0.01091345
- -0.05305289
- -0.02427209
- -0.19975668
- -1.71692859
- -1.53677781
- -3.89987009
- -10.70940462
- -6.71693816
- -0.28102249
- -8.86944824
- -7.95762687
- -7.13041437
- -6.64620014
- -5.11482482
- -4.42548227
- 0.00848295
- -0.06956227
- -2.6748853
- -2.21153293
- -1.67367741
- -1.07636151
- -0.79009981
- -0.16387243
- -0.18164401
- -0.04122529
- -0.00041833
- -0.05259382
- -0.0934314
- -0.11023834
- -0.10039175
- -0.06069209
- 0.01790437
- -0.04694024
- 0.00334084
- -0.06030621
- -0.58793619
- -1.27821808
- -4.97483577
- -5.66985655
- -8.43154622
- -11.15001317
- -12.95770812
- 0.0
- -14.47602729
- 0.0
odac_elem_refs:
- 0.0
- -1.11737936
- -0.00011835
- -0.2941727
- -0.03868426
- -0.34862832
- -1.31552566
- -3.12457285
- -1.6052078
- -0.49653389
- -0.01137327
- -0.21957281
- -0.0008343
- -0.2750172
- -0.88417265
- -1.887378
- -0.94903558
- -0.31628167
- -0.02014536
- -0.15901053
- -0.00731884
- -1.96521355
- -1.89045209
- -2.53057428
- -5.43600675
- -5.09739336
- -3.03088746
- -1.23786562
- -0.40650749
- -0.2416017
- -0.01139188
- -0.26282496
- -0.82446455
- -1.70237206
- -0.84245376
- -0.28544892
- -0.02239991
- -0.14115912
- -0.02840799
- -2.09540994
- -1.85863996
- -1.12257399
- -4.32965355
- -3.30670045
- -1.19460755
- -1.26257601
- -1.46832888
- -0.19779414
- -0.0144274
- -0.23668767
- -0.70836953
- -1.43186113
- -0.71701186
- -0.24883129
- -0.01118184
- -0.13173447
- -0.0318395
- -0.41195547
- -1.23134873
- -2.03082996
- 0.1375954
- -5.45866275
- -7.59139905
- -5.99965965
- -8.43495767
- -2.6578407
- -7.77349787
- -5.30762201
- -5.15109657
- -4.41466995
- -0.02995219
- -0.2544495
- -3.23821202
- -3.45887214
- -4.53635003
- -4.60979468
- -2.90707964
- -1.28286153
- -0.57716664
- -0.18337108
- -0.01135944
- -0.22045398
- -0.66150479
- -1.32506342
- -0.66500178
- -0.22643927
- -0.00728197
- -0.11208472
- -0.00757856
- -0.21798637
- -0.91078787
- -1.78187161
- -3.89912261
- -3.94192659
- -7.59026042
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
omat_elem_refs:
- 0.0
- -1.11700253
- 0.00079886
- -0.29731164
- -0.04129868
- -0.29106192
- -1.27751531
- -3.12342715
- -1.54797136
- -0.43969356
- -0.01250908
- -0.22855413
- -0.00943179
- -0.21707638
- -0.82619133
- -1.88667434
- -0.89093583
- -0.25816211
- -0.02414768
- -0.17662425
- -0.02568319
- -2.13001165
- -2.38688845
- -3.55934233
- -5.44700879
- -5.14749562
- -3.30662847
- -1.42167737
- -0.63181379
- -0.23449167
- -0.01146636
- -0.21291259
- -0.77939897
- -1.70148487
- -0.78386705
- -0.22690657
- -0.02245409
- -0.16092396
- -0.02798717
- -2.25685695
- -2.23690495
- -2.15347771
- -4.60251809
- -3.36416792
- -2.23062607
- -1.15550917
- -1.47553527
- -0.19918102
- -0.01475888
- -0.19767692
- -0.68005773
- -1.43073368
- -0.65790462
- -0.18915279
- -0.01179476
- -0.13507902
- -0.03056979
- -0.36017439
- -0.86279246
- -0.20573327
- -0.2734463
- -0.20046965
- -0.25444338
- -8.37972664
- -9.58424928
- -0.19466184
- -0.24860115
- -0.19531288
- -0.15401392
- -0.14577898
- -0.19655747
- -0.15645898
- -3.49380556
- -3.5317097
- -4.57108006
- -4.63425205
- -2.88247063
- -1.45679675
- -0.50290184
- -0.18521704
- -0.01123956
- -0.17483649
- -0.63132037
- -1.3248562
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- -0.24135757
- -1.04601971
- -2.04574044
- -3.84544799
- -7.28626119
- -7.3136314
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
omol_elem_refs:
    1:
        0: -13.445584057373376
    2:
        0: -78.82028064861346
    3:
        0: -203.32566089610248
        1: -197.98591238912647
    4:
        0: -398.94745406238457
        1: -389.9174065296533
        2: -371.64022062627583
    5:
        0: -670.7528161616635
    6:
        0: -1029.854128936652
    7:
        0: -1485.5420268052571
    8:
        0: -2042.9785186843171
    9:
        0: -2714.2404072902364
        -1: -2717.60644594991
    10:
        0: -3508.7435104433293
    11:
        0: -4415.24245175699
        1: -4410.114420604097
    12:
        0: -5443.89764689278
        2: -5421.144225327584
    13:
        0: -6594.618979783701
    14:
        0: -7873.6885552583635
    15:
        0: -9285.660195840774
    16:
        0: -10832.622363522705
    17:
        0: -12520.669728186529
        -1: -12524.311873124605
    18:
        0: -14354.279383593506
    19:
        0: -16323.548287099005
        1: -16319.331204963673
    20:
        0: -18436.4802235745
        2: -18418.670345940624
    21:
        0: -20696.184432436938
    22:
        0: -23110.540829573696
    23:
        0: -25682.996766371485
    24:
        0: -28418.38077740936
    25:
        0: -31317.9261898231
    26:
        0: -34383.42850178591
    27:
        0: -37623.47198155286
    28:
        0: -41039.92808633622
    29:
        0: -44637.390644693216
    30:
        0: -48417.15330794875
    31:
        0: -52373.88353905847
    32:
        0: -56512.7749670792
    33:
        0: -60836.15457735998
    34:
        0: -65344.29463090149
    35:
        0: -70041.24926492578
        -1: -70044.68577536294
    36:
        0: -74929.57000138272
    37:
        0: -653.6478304509429
        1: -649.6115598316848
    38:
        0: -833.3193042712877
    39:
        0: -1038.0281969578277
    40:
        0: -1273.9680039726502
    41:
        0: -1542.4549613021854
    42:
        0: -1850.7417570878108
    43:
        0: -2193.9167529178317
    44:
        0: -2577.187592352399
    45:
        0: -3004.13632479042
    46:
        0: -3477.528290952186
    47:
        0: -3997.318637706032
    48:
        0: -4563.758476480422
    49:
        0: -5171.823431250868
    50:
        0: -5828.85389738702
    51:
        0: -6535.615918982279
    52:
        0: -7291.548625930308
    53:
        0: -8099.879925553251
        -1: -8103.064621954474
    54:
        0: -8962.18002388331
    55:
        0: -546.0321954061023
        1: -542.2983307516248
    56:
        0: -690.6089668328505
    57:
        0: -854.1124475883443
    58:
        0: -12923.042210466992
    59:
        0: -14064.262597328401
    60:
        0: -15272.688366565537
    61:
        0: -16550.207110957523
    62:
        0: -17900.366871587325
    63:
        0: -19323.23592276476
    64:
        0: -20829.090486783083
    65:
        0: -22428.734746941605
    66:
        0: -24078.6824036755
    67:
        0: -25794.42345644991
    68:
        0: -27616.684560203954
    69:
        0: -29523.55544372604
    70:
        0: -31526.683164730683
    71:
        0: -33615.3810306281
    72:
        0: -1300.1780354638831
    73:
        0: -1544.4093860120772
    74:
        0: -1818.6231567944906
    75:
        0: -2123.144371335989
    76:
        0: -2461.7605162840764
    77:
        0: -2833.7631469210337
    78:
        0: -3242.7992608176864
    79:
        0: -3690.363355421551
    80:
        0: -4174.9981270766675
    81:
        0: -4691.757194525804
    82:
        0: -5245.360635715531
    83:
        0: -5838.120614817622
omc_elem_refs:
- 0.0
- -0.02831808
- 4.512e-05
- -0.03227157
- -0.03842519
- -0.05829283
- -0.0845041
- -0.08806738
- -0.09021346
- -0.06669846
- -0.01218631
- -0.03650269
- -0.00059093
- -0.05787736
- -0.08730952
- -0.0975534
- -0.09264199
- -0.07124762
- -0.02374602
- -0.05299112
- -0.02631476
- -1.7772147
- -1.25083444
- -0.79579447
- -0.49099317
- -0.31414986
- -0.20292182
- -0.14011632
- -0.09929659
- -0.03771207
- -0.01117902
- -0.06168715
- -0.08873364
- -0.09512942
- -0.09035978
- -0.06910849
- -0.02244872
- -0.05303651
- -0.02871903
- -1.94805417
- -1.33379896
- -0.69169331
- -0.26184306
- -0.20631599
- -0.48251608
- -0.96911893
- -1.47569462
- -0.03845194
- -0.0142445
- -0.07118991
- -0.09940292
- -0.09235056
- -0.08755943
- -0.06544925
- -0.01246646
- -0.04692937
- -0.03225123
- -0.26086039
- -27.20024339
- -0.08412926
- -0.08225924
- -0.07799715
- -0.07806185
- 0.00043759
- -0.07459766
- 0.0
- -0.06842841
- -0.07758266
- -0.07025152
- -0.08055003
- -0.07118177
- -0.07159568
- -2.69202862
- -2.21926765
- -1.679756
- -1.06135075
- -0.4554231
- -0.14488432
- -0.18377098
- -0.03603118
- -0.01076585
- -0.06381411
- -0.0905623
- -0.10095787
- -0.09501217
- -0.0574478
- -0.00599173
- -0.04134751
- -0.0082683
- -0.08704692
- -0.49656425
- -5.24233138
- -2.32542606
- -4.3376616
- -5.96430676
- 0.0
- 0.0
- -0.03842519
- 0.0
- 0.0
